<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">

    <style>
        body{
            font-family: DejaVu Sans, sans-serif;
            font-size:12px;
            color:#333;
            line-height:1.4;
        }

        .header{
            text-align:center;
            border-bottom:2px solid #1e88e5;
            padding-bottom:15px;
            margin-bottom:20px;
        }

        .title{
            font-size:24px;
            color:#1e88e5;
            font-weight:bold;
        }

        .subtitle{
            font-size:14px;
            color:#666;
        }

        h3{
            background:#1e88e5;
            color:white;
            padding:6px;
            margin-top:20px;
            margin-bottom:10px;
        }

        table{
            width:100%;
            border-collapse:collapse;
            margin-bottom:15px;
        }

        td{
            padding:6px;
            vertical-align:top;
        }

        .label{
            width:180px;
            font-weight:bold;
            background:#f3f3f3;
        }

        .box{
            border:1px solid #ddd;
            padding:10px;
            min-height:60px;
            white-space: pre-line;
        }

        .vitals td{
            border:1px solid #ddd;
        }

        .footer{
            margin-top:60px;
            text-align:center;
            font-size:11px;
            color:#777;
        }

        .signature{
            margin-top:70px;
            text-align:center;
        }

        .line{
            width:250px;
            border-top:1px solid black;
            margin:auto;
            margin-bottom:8px;
        }

    </style>

</head>

<body>

<div class="header">

    {{-- Logo --}}
    {{-- <img src="{{ public_path('images/logo.png') }}" width="120"> --}}

    <div class="title">
        Nurse Valeria
    </div>

    <div class="subtitle">
        Intravenous Therapy Report
    </div>

</div>

<h3>Patient Information</h3>

<table>

<tr>
    <td class="label">Patient</td>
    <td>{{ $consultation->name }} {{ $consultation->last_name }}</td>
</tr>

<tr>
    <td class="label">Date of Birth</td>
    <td>{{ $consultation->date_of_birth }}</td>
</tr>

<tr>
    <td class="label">Phone</td>
    <td>{{ $consultation->phone }}</td>
</tr>

<tr>
    <td class="label">Email</td>
    <td>{{ $consultation->email }}</td>
</tr>

@if($consultation->patient && $consultation->patient->group)

<tr>
    <td class="label">Group</td>
    <td>{{ $consultation->patient->group->place }}</td>
</tr>

@endif

<tr>
    <td class="label">Registration Date</td>
    <td>{{ $consultation->registration_date }}</td>
</tr>

</table>

<h3>Treatment</h3>

<table>

<tr>
    <td class="label">Treatment</td>
    <td>{{ optional($consultation->treatment)->name }}</td>
</tr>

<tr>
    <td class="label">Description</td>
    <td>{{ $consultation->treatment_description }}</td>
</tr>

<tr>
    <td class="label">Formula</td>
    <td>

        <div class="box">
            {{ $consultation->treatment_formula }}
        </div>

    </td>
</tr>

</table>

<h3>Notes</h3>

<div class="box">

{{ $consultation->notes }}

</div>

<h3>Vital Signs</h3>

<table class="vitals">

<tr style="background:#efefef;font-weight:bold;">
    <td></td>
    <td>Before Treatment</td>
    <td>After Treatment</td>
</tr>

<tr>
    <td><strong>Heart Rate</strong></td>
    <td>{{ $consultation->pre_heart_rate }} bpm</td>
    <td>{{ $consultation->heart_rate }} bpm</td>
</tr>

<tr>
    <td><strong>O₂ Saturation</strong></td>
    <td>{{ $consultation->pre_oxygen_saturation }} %</td>
    <td>{{ $consultation->oxygen_saturation }} %</td>
</tr>

<tr>
    <td><strong>Temperature</strong></td>
    <td>{{ $consultation->pre_temperature }} °C</td>
    <td>{{ $consultation->temperature }} °C</td>
</tr>

<tr>
    <td><strong>Blood Pressure</strong></td>
    <td>{{ $consultation->pre_blood_pressure }}</td>
    <td>{{ $consultation->blood_pressure }}</td>
</tr>

</table>

<div class="signature">

<div class="line"></div>

<strong>Nurse Signature</strong>

</div>

<div class="footer">

This document was generated by Nurse Valeria System.

</div>

</body>
</html>